spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    properties:
      username: ${KAFKA_USERNAME}
      password: ${KAFKA_PASSWORD}
      security:
        protocol: SASL_SSL
    sasl:
      mechanism: SCRAM-SHA-256
  liquibase:
    change-log: classpath:/liquibase/dbchangelog.xml

app:
  topic:
    orders-from-foundry: 82jesyk2-orders-from-foundry82jesyk2-orders-from-foundry
    foundry-product-produced: 82jesyk2-foundry-product-produced
    mass-to-foundry: 82jesyk2-mass-to-foundry

server:
  port: 8081
debug: false
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG

---
spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /base

datebase: H2

datasource:
  url: jdbc:h2:~/dbTest
  username: konrad
  password:
  driver-class-name: org.h2.Driver

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

kafka:
  listen: false

---
spring:
  profiles: dev

datebase: MYSQL

datasource:
  url: ${DATABASE_URL}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.jdbc.Driver

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect

