spring:
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
      path: /base
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database-platform: H2

app:
  topic:
    orders-from-foundry: orders-from-foundry
    foundry-product-produced: foundry-product-produced
    mass-to-foundry: mass-to-foundry

server:
  port: 8081

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG

