spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    orders-from-foundry: orders-from-foundry
    foundry-product-produced: foundry-product-produced
    mass-to-foundry: mass-to-foundry

server:
  port: 8081

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG